apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nginx-letsencrypt
spec:
  acme:
    email: chengzw258@163.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef: # 私钥
      name: nginx-tls
    solvers:
    - http01:
        ingress:
          # cert-manager 会自动创建 Ingress 资源，并自动修改 Ingress 的资源 prod/web，以暴露校验所需的临时路径。
          # 指定自动创建的 Ingress 的 ingress class
          class: nginx