apiVersion: apps/v1
kind: Deployment
metadata:
  name: service0-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service0
      version: v2
  template:
    metadata:
      labels:
        app: service0
        version: v2
    spec:
      containers:
        - name: service0
          imagePullPolicy: Always
          image: cr7258/service0:v2
          ports:
            - containerPort: 80