apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
  namespace: default  # 和代理的应用在同一个命名空间
spec:
  ingressClassName: nginx
  rules:
    - host: www.example.com # 域名
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: httpserver
              port:
                number: 8080
              